# Creating DataFrames

Many ways to do it!

In [1]:
import pandas as pd
import numpy as np

In [5]:
data = np.random.random(size=(5, 3))
print(data)

# Common 2D array and columns method
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.97699724 0.23250035 0.17454747]
 [0.11011626 0.90673085 0.37222005]
 [0.77665114 0.81701713 0.57427769]
 [0.34080801 0.09617229 0.26027026]
 [0.03694591 0.5385542  0.95945971]]


A         B         C
0  0.976997  0.232500  0.174547
1  0.110116  0.906731  0.372220
2  0.776651  0.817017  0.574278
3  0.340808  0.096172  0.260270
4  0.036946  0.538554  0.959460

In [6]:
# A dictionary of columns
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [9]:
# Or a list of rows (ie tuples) with a dtype
dtype = [("A", np.int), ("B", (np.str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [10]:
# Or the dictionary based version of list of rows
data = [{"A": 1, "B": "Sam"}, {"A": 2, "B": "Alex"}, {"A": 3, "B": "John"}]
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John